---
- name: Notify and Handlers Example
  hosts: all
  become: yes
  gather_facts: no

  tasks:
    - name: Installing Apache2
      apt:
        name: apache2
        update_cache: yes
        state: latest
    - name: Copy
      copy:
        src: /home/bkash8/ansible-project/index.html
        dest: /var/www/html
      notify:
        - Start Apache2 service
  handlers:
    - name: Start Apache2 service
      service:
        name: apache2
        state: restarted
