---
- name: Install Apache Tomcat
  hosts: ubuntu
  become: yes
  vars:
    tomcat_version: 10.1.49
    tomcat_url: "https://dlcdn.apache.org/tomcat/tomcat-10/v10.1.49/bin/apache-tomcat-10.1.49-fulldocs.tar.gz"
    tomcat_install_dir: /opt/tomcat
    tomcat_user: tomcat
    tomcat_group: tomcat
    shutdown_port: 8005
    shutdown_command: "SHUTDOWN"
    http_port: 8080
    https_port: 8443
    default_host: "localhost"

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name:
          - default-jdk
          - wget
        state: present

    - name: Create a tomcat group
      group:
        name: "{{ tomcat_group }}"
        state: present

    - name: Create a tomcat user
      user:
        name: "{{ tomcat_user }}"
        group: "{{ tomcat_group }}"
        home: "{{ tomcat_install_dir }}"
        shell: /bin/false
        state: present

    - name: Create installation directory
      file:
        path: "{{ tomcat_install_dir }}"
        state: directory
        owner: "{{ tomcat_user }}"
        group: "{{ tomcat_group }}"

    - name: Download Apache Tomcat
      get_url:
        url: "{{ tomcat_url }}"
        dest: "/tmp/apache-tomcat-{{ tomcat_version }}.tar.gz"
        mode: 0755

    - name: Extract Apache Tomcat
      unarchive:
        src: "/tmp/apache-tomcat-{{ tomcat_version }}.tar.gz"
        dest: "{{ tomcat_install_dir }}"
        owner: "{{ tomcat_user }}"
        group: "{{ tomcat_group }}"
        remote_src: yes
        extra_opts: [--strip-components=1]

    - name: Set permission on installation directory
      file:
        path: "{{ tomcat_install_dir }}"
        state: directory
        owner: "{{ tomcat_user }}"
        group: "{{ tomcat_group }}"
        recurse: yes
        mode: '0755'

    - name : Create a systemd service file for Tomcat
      template:
        src: server.xml.j2
        dest: /etc/systemd/system/tomcat.service
        owner: root
        group: root
        mode: '0644'

    - name: reload systemd daemon
      systemd:
        daemon_reload: yes

    - name: Start & enable Tomcat service
      systemd:
        name: tomcat
        enabled: yes
        state: restarted
