- name: Setup Webserver on Ubuntu
  hosts: ubuntu1
  become: yes
  tasks:
    - name: Install Apache2
      apt:
        name: apache2
        state: present
    - name: Start & Enable apache2
      service:
        name: apache2
        state: started
        enabled: yes
    - name: Copy Files
      copy:
        src: index.html
        dest: /var/www/html/index.html
